### PR TITLE
Support for .NET Standard

### LINKED ISSUE #26: Upgrade build targets
As @mchaloupka noticed, r2rml4net no longer builds in VS 2017.

@mchaloupka, are we fine with support for `net452`. If Resourcer was replaced with manual handling of embedded resource, we could go down to .NET 4.5.

`netstandard1.5` will only be possible with dotNetRDF 2+. How about that?

Here's what needs to be done:

* [x] convert projects to new csproj format
* [ ] replace StyleCop msbuild task with Roslyn Analyzers
* [x] move unspecified stuff into csproj
* [x] replace Zoltu.Versioning with GitVersion
* [x] also, set up appveyor instead of old TC

### PR DESCRIPTION
**Pull request by tpluscode**
closes #26

### CODE REVIEW

**Comment by mchaloupka** [comment]
According to the build it looks like you have some issue with `AssemblyFileVersionAttribute` (probably added additional one using the tool). I do not understand why the build is not failed. Maybe it is needed to have it as separate steps (build and pack). I do not know.

**Comment by tpluscode** [comment]
About symbols, I've previously used GitLink. Will see to configure this here as well.

**Comment by tpluscode** [comment]
@mchaloupka, while I battle dependencies which act weird with dotnet tooling, please tell me if targeting .NET Standard 2.0 and .NET Framework 4 would be good enough? I wanted to do .NET Standard 1.5 but it lack some APIs which may or may not be required (wait till I run tests against the official suite)

**Comment by mchaloupka** [comment]
.NET Standard 2.0 seems completely fine to me. I guess that .NET 4 is currently needed only on Windows PosReady 2009 (which will be out of support 2019Q2), so I would be even ok if you will target some higher .NET version.

**Comment by mchaloupka** [comment]
It seems like you are missing `dotnet-xunit` in `TCode.r2rml4net.Mapping.Tests\paket.references`. Otherwise it looks almost done. Or do you have any additional plans what you want to add?

**Comment by tpluscode** [comment]
Indeed I missed that, thanks.

> any additional plans

GitLink has issues with dotnet tooling so I'll make a new ticket for that.
I will also want to run the w3c test suite on AppVeyor but this can be handled separately.
Finally there's StyleCop but it's not that important either.

I think I'm almost done here :)

**Comment by mchaloupka** [comment]
One more thing I noticed is that you are creating two nuget packages. Is that intentional?

**Comment by tpluscode** [comment]
Nope. It's actually something that I accidentally committed

**Comment by mchaloupka** [comment]
You can also update the badge in the Readme.md.

Please publish the nuget so I can start using the official one instead of local copy taken from the build.

**Pull request merged**
